theme: vertx-howtos-jekyll-theme
url: https://vertx-howtos.github.io/web-and-oauth2-oidc

asciidoctor:
  attributes:
    source-highlighter: rouge
    rouge-css: style

exclude:
  - LICENSE
  - build*
  - pom.xml
  - target
  - src
  - Gemfile*
